// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobY_R3qXarzt98mImgXSVhC3kldmiH3Q',
    appId: '1:248507979769:web:a12108955275558a378f28',
    messagingSenderId: '248507979769',
    projectId: 'todo-9895a',
    authDomain: 'todo-9895a.firebaseapp.com',
    storageBucket: 'todo-9895a.appspot.com',
    measurementId: 'G-N4QLD1VGX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAop3t4enxtm-qEDpfRiHKJNLHzZ1ZaCU',
    appId: '1:248507979769:android:8cdc3c6a6311ec79378f28',
    messagingSenderId: '248507979769',
    projectId: 'todo-9895a',
    storageBucket: 'todo-9895a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQjdLNaDmQaJvPNPXC6L-28V29c_nAeg',
    appId: '1:248507979769:ios:e5375769168dcc3e378f28',
    messagingSenderId: '248507979769',
    projectId: 'todo-9895a',
    storageBucket: 'todo-9895a.appspot.com',
    iosClientId: '248507979769-kqi194olpaqqgh05rule95bvd60mp1ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtQjdLNaDmQaJvPNPXC6L-28V29c_nAeg',
    appId: '1:248507979769:ios:e5375769168dcc3e378f28',
    messagingSenderId: '248507979769',
    projectId: 'todo-9895a',
    storageBucket: 'todo-9895a.appspot.com',
    iosClientId: '248507979769-kqi194olpaqqgh05rule95bvd60mp1ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
